// kernel/build — the kernel from one C source to both of its homes:
//   kernel/build/libdeclarekernel.a   (native, the Mac/iOS hosts link it)
//   kernel/build/kernel.wasm          (the browser instantiates it)
// plus a native test binary. Apple clang targets wasm32; the linker is
// Homebrew lld (`brew install lld`). No libc on either side: the kernel is
// freestanding, allocation-free after load.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
// the kernel proper; `*_jsc.c` is the JavaScriptCore glue, built only by the Mac host (SwiftPM)
const SRC = readdirSync(path.join(HERE, "src")).filter((f) => f.endsWith(".c") && !f.endsWith("_jsc.c")).map((f) => path.join(HERE, "src", f));
const OUT = path.join(HERE, "build");
mkdirSync(OUT, { recursive: true });
const WASM_LD = ["/opt/homebrew/opt/lld/bin/wasm-ld", "/opt/homebrew/bin/wasm-ld"].find(existsSync);
const run = (cmd, args) => execFileSync(cmd, args, { stdio: ["ignore", "inherit", "inherit"] });
const COMMON = ["-std=c11", "-Wall", "-Wextra", "-Werror", "-ffreestanding", "-fno-builtin", "-nostdlib", `-I${path.join(HERE, "include")}`];
const only = process.argv[2];   // native | wasm | test | (all)

if (!only || only === "native" || only === "test") {
  const objs = [];
  for (const c of SRC) {
    const o = path.join(OUT, path.basename(c, ".c") + ".o");
    run("clang", [...COMMON, "-O2", "-c", c, "-o", o]); objs.push(o);
  }
  run("libtool", ["-static", "-o", path.join(OUT, "libdeclarekernel.a"), ...objs]);
  console.log(`kernel: libdeclarekernel.a (${statSync(path.join(OUT, "libdeclarekernel.a")).size} bytes)`);
}
if (!only || only === "wasm") {
  if (!WASM_LD) { console.error("kernel: wasm-ld not found — brew install lld"); process.exit(1); }
  const objs = [];
  for (const c of SRC) {
    const o = path.join(OUT, path.basename(c, ".c") + ".wasm.o");
    run("clang", [...COMMON, "--target=wasm32", "-Os", "-c", c, "-o", o]); objs.push(o);
  }
  const wasm = path.join(OUT, "kernel.wasm");
  // the ABI is the export list: every kernel_* function the header declares
  const header = readFileSync(path.join(HERE, "include/declare_kernel.h"), "utf8");
  const exports = [...header.matchAll(/\b(kernel_[a-z_0-9]+)\s*\(/g)].map((m) => "--export=" + m[1]);
  // __heap_base: where the loader places the arena (the first free byte after the kernel's own data)
  run(WASM_LD, ["--no-entry", "--strip-all", ...exports, "--export=__heap_base", "-o", wasm, ...objs]);
  // binaryen's wasm-opt, when installed (brew install binaryen): -Oz on top of clang's -Os
  const WASM_OPT = ["/opt/homebrew/bin/wasm-opt", "/usr/local/bin/wasm-opt"].find(existsSync);
  if (WASM_OPT) run(WASM_OPT, ["-Oz", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", wasm, "-o", wasm]);
  const b = readFileSync(wasm);
  console.log(`kernel: kernel.wasm ${b.length} bytes raw · ${gzipSync(b).length} gz`);
  // EMBED: the runtime carries the module as bytes (runtime/src/kernel-wasm.ts),
  // so every host loads it the same way and no bundle needs a second file.
  const ts = path.join(HERE, "../runtime/src/kernel-wasm.ts");
  const prev = existsSync(ts) ? readFileSync(ts, "utf8") : "";
  const next = `// GENERATED by kernel/build.mjs from kernel/src/kernel.c — do not edit.\n// kernel.wasm: ${b.length} bytes raw, ${gzipSync(b).length} gzipped.\nexport const KERNEL_WASM_B64 = "${b.toString("base64")}";\n`;
  if (next !== prev) { writeFileSync(ts, next); console.log(`kernel: wrote ${path.relative(path.join(HERE, ".."), ts)}`); }
}
// THE FILTER MODULE — a SEPARATE, optional WebAssembly module (kernel/filter/):
// the canvas `filter` fallback's pixel loops. Not part of the kernel, so a build
// that never filters in software carries none of it (declarec stubs
// canvas-filter.js, the only importer of runtime/src/filter-wasm.ts). SIMD128
// (Safari 16.4+, Chrome 91+); an engine that cannot compile it keeps the JS loops.
if (!only || only === "wasm" || only === "filter") {
  if (!WASM_LD) { console.error("kernel: wasm-ld not found — brew install lld"); process.exit(1); }
  const src = path.join(HERE, "filter/filter.c"), o = path.join(OUT, "filter.wasm.o"), wasm = path.join(OUT, "filter.wasm");
  run("clang", ["-std=c11", "-Wall", "-Wextra", "-Werror", "-ffreestanding", "-fno-builtin", "-nostdlib", "--target=wasm32", "-msimd128", "-O2", "-c", src, "-o", o]);
  run(WASM_LD, ["--no-entry", "--strip-all", "--export=filter_blur", "--export=filter_matrix", "--export=__heap_base", "-o", wasm, o]);
  const WASM_OPT = ["/opt/homebrew/bin/wasm-opt", "/usr/local/bin/wasm-opt"].find(existsSync);
  if (WASM_OPT) run(WASM_OPT, ["-O3", "--enable-simd", "--enable-bulk-memory", "--enable-nontrapping-float-to-int", wasm, "-o", wasm]);
  const b = readFileSync(wasm);
  console.log(`kernel: filter.wasm ${b.length} bytes raw · ${gzipSync(b).length} gz`);
  const ts = path.join(HERE, "../runtime/src/filter-wasm.ts");
  const prev = existsSync(ts) ? readFileSync(ts, "utf8") : "";
  const next = `// GENERATED by kernel/build.mjs from kernel/filter/filter.c — do not edit.\n// filter.wasm: ${b.length} bytes raw, ${gzipSync(b).length} gzipped. Imported ONLY by canvas-filter.ts.\nexport const FILTER_WASM_B64 = "${b.toString("base64")}";\n`;
  if (next !== prev) { writeFileSync(ts, next); console.log(`kernel: wrote ${path.relative(path.join(HERE, ".."), ts)}`); }
}
if (only === "test") {
  // the native test driver links the kernel with libc (it is a host program)
  const t = path.join(OUT, "kernel-test");
  run("clang", ["-std=c11", "-O1", "-g", "-Wall", `-I${path.join(HERE, "include")}`, path.join(HERE, "test/kernel-test.c"), path.join(OUT, "libdeclarekernel.a"), "-lm", "-o", t]);
  run(t, []);
}
