// GENERATED from library/themes/*.declare by tools/internal/gen-themes.mjs — DO NOT EDIT.
// The presets are authored in the language (stylesheet Name [ theme: Theme [ … ] ]);
// this module is their projection into the runtime, so the zero-declaration
// default (value.ts DEFAULT_THEME = THEME_RECORDS.SanFrancisco) and the named
// Themes.* surface serve the SAME objects the authored files declare.

export const THEME_RECORDS: Readonly<Record<string, Readonly<Record<string, unknown>>>> = Object.freeze({
  Cupertino: Object.freeze({
    bg: 0xF5F5F7,
    surface: 0xFFFFFF,
    line: 0xC6C6C8,
    text: 0x1D1D1F,
    textMuted: 0x6E6E73,
    textFaint: 0xAAB4BE,
    accent: 0x007AFF,
    accentText: 0xFFFFFF,
    control: 0xFFFFFF,
    controlActive: 0xE8F0FE,
    depth: 1,
    focusRing: true,
    controlRadius: 6,
    buttonRadius: 6,
    fieldRadius: 6,
    fieldPadding: 7,
    buttonHeight: 28,
    switchWidth: 40,
    switchHeight: 24,
    focusRingWidth: 3.5,
    focusRingGap: 0,
    checkboxSize: 14,
    checkboxRadius: 3.5,
    disabledOpacity: 0.5,
  }),
  CupertinoDark: Object.freeze({
    bg: 0x1E1E1E,
    surface: 0x2C2C2E,
    line: 0x48484A,
    text: 0xF2F2F7,
    textMuted: 0x98989D,
    textFaint: 0xAAB4BE,
    accent: 0x0A84FF,
    accentText: 0xFFFFFF,
    control: 0x3A3A3C,
    controlActive: 0x1C3D5F,
    depth: 1,
    focusRing: true,
    controlRadius: 6,
    buttonRadius: 6,
    fieldRadius: 6,
    fieldPadding: 7,
    buttonHeight: 28,
    switchWidth: 40,
    switchHeight: 24,
    focusRingWidth: 3.5,
    focusRingGap: 0,
    checkboxSize: 14,
    checkboxRadius: 3.5,
    disabledOpacity: 0.5,
  }),
  MountainView: Object.freeze({
    bg: 0xFFFBFE,
    surface: 0xFFFFFF,
    line: 0x79747E,
    text: 0x1C1B1F,
    textMuted: 0x49454F,
    textFaint: 0xAAB4BE,
    accent: 0x6750A4,
    accentText: 0xFFFFFF,
    control: 0xE7E0EC,
    controlActive: 0xE8DEF8,
    depth: 1,
    focusRing: true,
    controlRadius: 4,
    buttonRadius: 999,
    fieldRadius: 4,
    fieldPadding: 12,
    buttonHeight: 40,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbOff: 16,
    focusRingWidth: 3,
    focusRingGap: 2,
    sliderHandle: "bar",
    checkboxSize: 18,
    checkboxRadius: 2,
    disabledOpacity: 0.38,
  }),
  MountainViewDark: Object.freeze({
    bg: 0x141218,
    surface: 0x211F26,
    line: 0x938F99,
    text: 0xE6E0E9,
    textMuted: 0xCAC4D0,
    textFaint: 0xAAB4BE,
    accent: 0xD0BCFF,
    accentText: 0x381E72,
    control: 0x49454F,
    controlActive: 0x4A4458,
    depth: 1,
    focusRing: true,
    controlRadius: 4,
    buttonRadius: 999,
    fieldRadius: 4,
    fieldPadding: 12,
    buttonHeight: 40,
    switchWidth: 52,
    switchHeight: 32,
    switchThumbOff: 16,
    focusRingWidth: 3,
    focusRingGap: 2,
    sliderHandle: "bar",
    checkboxSize: 18,
    checkboxRadius: 2,
    disabledOpacity: 0.38,
  }),
  SanFrancisco: Object.freeze({
    bg: 0xF4F6FA,
    surface: 0xFFFFFF,
    line: 0xDBE1E9,
    text: 0x1B2733,
    textMuted: 0x6C7A88,
    textFaint: 0xAAB4BE,
    accent: 0x2E6FE0,
    accentText: 0xFFFFFF,
    control: 0xE7EBF1,
    controlActive: 0xD3E2FC,
    depth: 1,
    focusRing: true,
    controlRadius: 7,
  }),
  SanFranciscoDark: Object.freeze({
    bg: 0x0F1620,
    surface: 0x18212C,
    line: 0x2A3642,
    text: 0xE7EEF2,
    textMuted: 0x9DB0BC,
    textFaint: 0x556673,
    accent: 0x4C8DFF,
    accentText: 0xFFFFFF,
    control: 0x223040,
    controlActive: 0x1F3B54,
    depth: 1,
    focusRing: true,
    controlRadius: 7,
  }),
});
