import { assert, test, summarize, withCausal, ready, saved } from './persistence-support.mjs';
await test('accepted edits coalesce to an acknowledged override-only envelope', () => withCausal(async ({ openApp }) => {
  const a = await openApp({ width: 1280, height: 800 }); await ready(a);
  await a.page.evaluate(() => { __app.selectScenario('fuelShock'); __app.selectFactor('jetFuelPrice'); });
  assert.equal(await a.page.evaluate(() => __app.draft.savedRecord.disk.revision), 0);
  await a.page.evaluate(() => { __app.changeSelectedAssumption(4.2); __app.changeSelectedAssumption(4.25); });
  await saved(a);
  const first = await a.page.evaluate(() => __app.draft.savedRecord.value);
  assert.equal(first.workingSourceId, 'fuelShock');
  assert.deepEqual(first.overrides, { jetFuelPrice: 4.25 });
  assert.equal(new Date(first.savedAt).toISOString(), first.savedAt);
  await a.page.evaluate(() => { __app.assumptionDraft = 'garbage'; __app.commitAssumptionDraft(); });
  assert.equal(await a.page.evaluate(() => __app.draft.workingGeneration), 2);
  assert.deepEqual(await a.page.evaluate(() => __app.draft.savedRecord.value), first);
  await a.page.evaluate(() => { __app.assumptionDraft = '$4.35'; __app.commitAssumptionDraft(); });
  await saved(a);
  assert.equal(await a.page.evaluate(() => __app.draft.savedRecord.value.overrides.jetFuelPrice), 4.35);
  await a.page.evaluate(() => __app.resetSelectedAssumption()); await saved(a);
  assert.deepEqual(await a.page.evaluate(() => __app.draft.savedRecord.value.overrides), {});
  await a.page.close();
  const b = await openApp(); await ready(b);
  assert.equal(await b.page.evaluate(() => __app.draft.validation.record.workingSourceId), 'fuelShock');
  assert.deepEqual(a.pageErrors, []); assert.deepEqual(b.pageErrors, []);
}));
await test('old receipt cannot mark newer Working data saved', () => withCausal(async ({ openApp }) => {
  const a = await openApp(); await ready(a);
  await a.page.evaluate(() => { __persistenceTest.hold = true; __app.selectFactor('jetFuelPrice'); __app.changeSelectedAssumption(4); });
  await a.page.waitForFunction(() => __app.draft.savedRecord.disk.pending);
  await a.page.evaluate(() => __persistenceTest.clock.advance(1000));
  await a.page.waitForFunction(() => __persistenceTest.pending.length === 1);
  assert.equal(await a.page.evaluate(() => __app.draft.saved), false);
  await a.page.evaluate(() => __app.changeSelectedAssumption(4.5));
  await a.page.waitForFunction(() => __app.draft.stagedWorkingGeneration === 2);
  await a.page.evaluate(() => __persistenceTest.release());
  await a.page.waitForFunction(() => __app.draft.savedRecord.disk.savedRevision >= 1);
  assert.equal(await a.page.evaluate(() => __app.draft.saved), false);
  await a.page.evaluate(() => { __persistenceTest.hold = false; __persistenceTest.clock.advance(1000); });
  await saved(a);
  assert.equal(await a.page.evaluate(() => __app.draft.savedRecord.value.overrides.jetFuelPrice), 4.5);
}, { persistenceModule: '/test/helpers/persistence-browser-controls.mjs' }));
summarize('causal-desk persistence save');
