// tools/prebuild.mjs — precompile EVERY example into a committed artifact the
// static site loads by default (GitHub Pages, no compiler download in the common
// case). One artifact per example, mirroring what the dev server's hostPage does
// so the static and dynamic pages match. For each examples/<name>/<name>.declare:
//
//   - compileTracked() → compiled program + the dependency CLOSURE (the main file,
//     every include, every auto-included library, the manifest). The closure is
//     baked with CONTENT-HASH validators + root-relative ids, so a dumb static
//     host can re-probe it (fetch + fnv1a) to answer "is the source newer than the
//     artifact?" with NO compiler — see web/boot-static.js.
//   - the auto-include LIBRARY (manifest + its src) is baked in too, so the
//     in-browser compiler can resolve bare tags (`Bar [ … ]`) on a live edit
//     without a second fetch.
//   - demos (site only): each demo's comment-stripped source (seed) + precompiled
//     preview, exactly like the server.
//   - a per-example static index.html (except the site, whose page is the repo-root
//     index.html) that boots the artifact via web/boot-static.js.
//
//   node tools/prebuild.mjs

import path from "node:path";
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { compile, compileTracked, fnv1a } from "../compiler/dist/compile-node.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const EXAMPLES = path.join(ROOT, "examples");
const RUNTIME_GZ_BYTES = 45 * 1024; // the runtime's real shipping weight (see server/index.mjs)

// Same comment-strip the editor seeds use, so a precompiled preview matches what an
// untouched editor would compile.
const stripComments = (s) =>
  s.split("\n").filter((l) => !l.trim().startsWith("//")).join("\n")
    .replace(/^\s+/, "").replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "") + "\n";

const fail = (label, c) => {
  if (c.errors?.length) throw new Error(`prebuild: ${label} did not compile:\n` +
    c.errors.map((e) => "  " + (e.pos?.line != null ? `line ${e.pos.line}: ` : "") + e.message).join("\n"));
};

/** Absolute path → root-relative POSIX URL (the id a browser fetch resolves against ROOT). */
const relURL = (abs) => path.relative(ROOT, abs).split(path.sep).join("/");

/** Bake a compile's closure for the browser: root-relative ids + content-hash
 *  validators (the universal floor — no mtime/ETag dependence, works on any host). */
function bakeClosure(closure) {
  return {
    props: closure.props,
    entries: closure.entries.map((e) => {
      const id = relURL(e.id);
      if (e.v.missing) return { id, kind: e.kind, v: { missing: true } };
      try { return { id, kind: e.kind, v: { hash: fnv1a(readFileSync(e.id, "utf8")) } }; }
      catch { return { id, kind: e.kind, v: { missing: true } }; }
    }),
  };
}

/** The auto-include library, prefetched: the manifest + each src file it names,
 *  keyed the way the browser memoryHost expects ("library/src/<file>"). */
function bakeLibrary() {
  let manifest = {};
  try { manifest = JSON.parse(readFileSync(path.join(ROOT, "library/autoincludes.json"), "utf8")); } catch {}
  const files = {};
  for (const rel of Object.values(manifest)) {
    try { files["library/src/" + rel] = readFileSync(path.join(ROOT, "library/src", rel), "utf8"); } catch {}
  }
  return { manifest, files };
}

const ARTIFACT_HEADER =
  "// GENERATED by tools/prebuild.mjs — do not edit. The static page loads this\n" +
  "// precompiled artifact by default; web/boot-static.js re-probes closure for staleness.\n";

const exampleIndexHtml = (name) => `<!doctype html>
<meta charset="utf-8">
<title>${name} · Declare</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<link rel="icon" type="image/svg+xml" href="../../favicon.svg">
<link rel="icon" type="image/png" sizes="256x256" href="../../favicon.png">
<link rel="apple-touch-icon" href="../../apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Declare">
<meta property="og:title" content="${name} · Declare">
<meta property="og:image" content="https://davidtemkin.github.io/declarelang/og-image.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image" content="https://davidtemkin.github.io/declarelang/og-image.png">
<style>html,body{margin:0;padding:0;background:#0B141B}</style>
<div id="host"></div>
<script type="module">
  // Rendered from a committed precompiled artifact — no compiler needed to view it.
  // boot-static.js re-checks the dependency closure and warm-loads the in-browser
  // compiler in the background (only used if the source moved, or on a live edit).
  import boot from "../../web/boot-static.js";
  import artifact from "./prebuilt/${name}.js";
  boot(artifact);
</script>
`;

const library = bakeLibrary();

function buildExample(name) {
  const dir = path.join(EXAMPLES, name);
  const appFile = path.join(dir, name + ".declare");
  const src = readFileSync(appFile, "utf8");

  const tracked = compileTracked(src, { originDir: dir, mainId: appFile, props: { backend: "dom" } });
  fail(name + ".declare", tracked);

  const pageWeight = Math.round((RUNTIME_GZ_BYTES + gzipSync(tracked.source).length) / 1024);
  const sourceLines = src.split("\n").filter((l) => { const t = l.trim(); return t !== "" && !t.startsWith("//"); }).length;

  // demos: seed (comment-stripped) + precompiled preview — present only where an
  // example ships a demos/ dir (the site does; the flagship apps don't).
  const seeds = {}, precompiled = {};
  const demoDir = path.join(dir, "demos");
  if (existsSync(demoDir)) {
    for (const f of readdirSync(demoDir).sort()) {
      if (!f.endsWith(".declare")) continue;
      const dn = f.slice(0, -8);
      const stripped = stripComments(readFileSync(path.join(demoDir, f), "utf8"));
      const cr = compile(stripped, {}); // matches the server's POST /compile (no originDir)
      fail(`demo ${dn}`, cr);
      seeds[dn] = stripped;
      precompiled[dn] = cr.source;
    }
  }
  seeds.__page__ = src; // the whole-page editor shows the page's own raw source

  const artifact = {
    backend: "DomBackend",
    source: tracked.source,
    pageWeight, sourceLines,
    seeds, precompiled,
    library,                              // prefetched auto-include set for in-browser compiles
    closure: bakeClosure(tracked.closure), // dependency graph + hash validators for freshness
    mainId: relURL(appFile),               // recompiled in-browser if the closure probe says stale
  };

  const outDir = path.join(dir, "prebuilt");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(path.join(outDir, name + ".js"), ARTIFACT_HEADER + "export default " + JSON.stringify(artifact) + ";\n");

  // The site's page is the repo-root index.html (hand-authored, with SEO meta); every
  // other example gets a generated static index.html next to its sources.
  if (name !== "site") writeFileSync(path.join(dir, "index.html"), exampleIndexHtml(name));

  return { name, program: tracked.source.length, demos: Object.keys(precompiled).length, pageWeight, sourceLines, deps: artifact.closure.entries.length };
}

// Every examples/<name>/ that contains <name>.declare.
const names = readdirSync(EXAMPLES).filter((n) => existsSync(path.join(EXAMPLES, n, `${n}.declare`))).sort();
console.log(`prebuild: ${names.length} example(s), library {${Object.keys(library.manifest).join(", ") || "empty"}}`);
for (const name of names) {
  const r = buildExample(name);
  console.log(`  ${r.name.padEnd(12)} ${(r.program / 1024).toFixed(1).padStart(6)} KB · ${String(r.demos).padStart(2)} demos · ${String(r.pageWeight).padStart(3)} KB gz · ${String(r.sourceLines).padStart(4)} LOC · ${r.deps} dep(s)`);
}
